micronaut:
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowCredentials: true
          allowedMethods:
            - OPTIONS
            - POST
            - PUT
            - GET
            - DELETE
          exposedHeaders:
            - Access-Control-Allow-Origin
            - Access-Control-Allow-Headers
            - Access-Control-Request-Method
            - Access-Control-Request-Headers
            - Origin
            - Cache-Control
            - Content-Type
            - Authorization
  application:
    name: demoTest
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: naoseiquequeeuvootaaquimaiquiinfernoessecagulotemquesermuitogrande
    intercept-url-map:
      -
        pattern: "/api/admin/**"
        http-method: POST
        access:
          - isAnonymous()
      - pattern: "/api/admin/**"
        http-method: GET
        access:
          - isAnonymous()
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut?useSSL=false
    driverClassName: org.postgresql.Driver
    username: datdv
    password: 123456
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
    maxActiveConnections: 5
jpa:
  default:
    entity-scan:
      classpath: true
      packages: 'com.example'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        enable_lazy_load_no_trans: true
#endpoints:
#  health:
#    enabled: true
#    details-visible: ANONYMOUS
