micronaut:
  application:
    name: demoTest
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    authentication: bearer
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: naoseiquequeeuvootaaquimaiquiinfernoessecagulotemquesermuitogrande
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut?useSSL=false
    driverClassName: org.postgresql.Driver
    username: datdv
    password: 123456
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
    maxActiveConnections: 5
jpa:
  default:
    entity-scan:
      classpath: true
      packages: 'com.example'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        enable_lazy_load_no_trans: true
endpoints:
  health:
    enabled: true
    details-visible: ANONYMOUS
